# action.yml
name: 'ClearML get task stats'
description: 'Clone and enqueue your task to train your model'
inputs:
  CLEARML_API_ACCESS_KEY:
    description: 'ClearML api access key (can be generated in your profile page'
    required: true
  CLEARML_API_SECRET_KEY:
    description: 'ClearML api secret key (can be generated in your profile page'
    required: true
  CLEARML_API_HOST:
    description: 'ClearML server api host'
    required: true
  TASK_ID:
    description: 'The task id you would like to get the stats'
    required: true
branding:
  color: 'purple'
  icon: 'monitor'
runs:
  using: 'docker'
  image: 'Dockerfile'
